# Generated by Django 2.2 on 2020-11-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0002_brand_category_order_orderitem_product_productitem_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='qty',
        ),
    ]
