# Generated by Django 2.2 on 2020-11-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0004_auto_20201119_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_item_id',
            field=models.IntegerField(default=0),
        ),
    ]
