# Generated by Django 2.2 on 2020-11-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0005_orderitem_order_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date_added',)},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='productitem',
            new_name='product_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
